### ISSUE TITLE
Team select architectural approach for project 1

### ISSUE THREAD

**Issue by majway27** [BeerLiftersAssociation/infrastructure#2]
Go over proposed architectural approaches for project 1, as suggested by team.

https://beerliftersassociation.github.io/design-project1

Target 12/3

**Comment by majway27** [comment]
This is ready for review.
My preference is **3**,2,1

**Comment by vedran3** [comment]
My preference is 1, 5, 3 but I am ok with any of theses project ideas that we agree on ⚡️

**Comment by majway27** [comment]
@vedran3, thank you for looking at this.

This one is different than the app idea ask.  It is for a high-level technical design of our project one stack.  Please see the [link](https://beerliftersassociation.github.io/design-project1) in my first comment, it has 3 options for technology selection in AWS.

As noted above my preference order is 3,2,1.  I'd also really like your input.  I had this one targeted for 11/30 to keep our cadence up, so I'll try to button this one up NLT Monday 12/3.

@JBluesify - same :)

**Comment by vedran3** [comment]
My bad, I'm getting used to the GH interface and am starting to understand it better now :) 

My preference is 3,2,1 also. I really like the GraphQL idea for a backend after reading about it for a bit now. Looks really cool and seems to be the most modern approach. Cost will be cheaper also, being serverless

**Comment by majway27** [comment]
Excellent, let's target *3*.

**Comment by JBluesify** [comment]
Sorry for my late review.  I would go 3-2-1 as well.  I compared 2 and 3.  Looks to me that 3 is the best way to go because I understood the flow better than 2.  And AppSync looks to be more manageable  than API Gateway (as what I gathered from AWS site). :-)

**Comment by majway27** [comment]
np - thank you @JBluesify
