### ISSUE TITLE
SOP and Tags approach [12/7]

### ISSUE THREAD

**Issue by majway27** [BeerLiftersAssociation/infrastructure#3]
https://github.com/BeerLiftersAssociation/infrastructure/wiki

Please let me know if you see any issues with these proposed policies.

Targeting 12/7 for implementation.

**Comment by vedran3** [comment]
@majway27 I see this ticket (I think it's a ticket) but I am not sure what needs to be done and where? 

Also, I am a fresh off the press newbie with GitHub, so I am not sure 100% how to use GitHub in terms of completing a request 

Thanks Robbie

**Comment by majway27** [comment]
@vedran3, thanks for looking at this.  The first comment of this issue has a link to two wiki pages on the infrastructure repo.  If you could look at those and let me know if they look good.  Feel free to update, add, etc.
I'm targeting 12/7 to call those official.
@JBluesify - same :)

**Comment by vedran3** [comment]
The 2 docs look good to me. As an SOP topic, what IDE would you recommend we use for this work? There might be one you worked with before that would work well for this. If this is not relevant as we may only be using text files to push up to git locally, then let me know. 

The only other thing is we could add the tools that we would be using for the scope of the project. I can add some also.

**Comment by majway27** [comment]
Good questions.  For AWS configuration and python stuff, I think pycharm is a great tool.
For front end work, I like using cloud9, since all the npm stuff just works.  If you get involved in the front end stuff, I can offer assistance getting a Dev environment setup.
Tool suggestions sound good.
